name: common_tools
description: Tools

version: 1.0.0

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  package_info_plus:
  device_info_plus:
  url_launcher: 6.1.10
  mmkv:
  dio: 5.5.0+1
  intl: 0.18.0
  path_provider: 2.1.3
  encrypt: 5.0.1
  flutter_downloader:
  open_file_plus: 3.4.1
  permission_handler: 11.3.1
  flutter_xlog:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.ws.tool.common_tools
        pluginClass: WsToolPlugin
      ios:
        pluginClass: XpToolPlugin

